//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFORMKLShop.ServiceReferenceDanhMucSP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DanhMucSP", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceKLShop")]
    [System.SerializableAttribute()]
    public partial class DanhMucSP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDM {
            get {
                return this.MaDMField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDMField, value) != true)) {
                    this.MaDMField = value;
                    this.RaisePropertyChanged("MaDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDM {
            get {
                return this.TenDMField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDMField, value) != true)) {
                    this.TenDMField = value;
                    this.RaisePropertyChanged("TenDM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDanhMucSP.IServiceDanhMucSP")]
    public interface IServiceDanhMucSP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMucSP/All", ReplyAction="http://tempuri.org/IServiceDanhMucSP/AllResponse")]
        WFORMKLShop.ServiceReferenceDanhMucSP.DanhMucSP[] All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMucSP/All", ReplyAction="http://tempuri.org/IServiceDanhMucSP/AllResponse")]
        System.Threading.Tasks.Task<WFORMKLShop.ServiceReferenceDanhMucSP.DanhMucSP[]> AllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMucSP/SuaDanhMuc", ReplyAction="http://tempuri.org/IServiceDanhMucSP/SuaDanhMucResponse")]
        bool SuaDanhMuc(string madm, string tendm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMucSP/SuaDanhMuc", ReplyAction="http://tempuri.org/IServiceDanhMucSP/SuaDanhMucResponse")]
        System.Threading.Tasks.Task<bool> SuaDanhMucAsync(string madm, string tendm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMucSP/XoaDanhMuc", ReplyAction="http://tempuri.org/IServiceDanhMucSP/XoaDanhMucResponse")]
        bool XoaDanhMuc(string madm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMucSP/XoaDanhMuc", ReplyAction="http://tempuri.org/IServiceDanhMucSP/XoaDanhMucResponse")]
        System.Threading.Tasks.Task<bool> XoaDanhMucAsync(string madm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMucSP/ThemDanhMuc", ReplyAction="http://tempuri.org/IServiceDanhMucSP/ThemDanhMucResponse")]
        bool ThemDanhMuc(string madm, string tendm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMucSP/ThemDanhMuc", ReplyAction="http://tempuri.org/IServiceDanhMucSP/ThemDanhMucResponse")]
        System.Threading.Tasks.Task<bool> ThemDanhMucAsync(string madm, string tendm);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDanhMucSPChannel : WFORMKLShop.ServiceReferenceDanhMucSP.IServiceDanhMucSP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDanhMucSPClient : System.ServiceModel.ClientBase<WFORMKLShop.ServiceReferenceDanhMucSP.IServiceDanhMucSP>, WFORMKLShop.ServiceReferenceDanhMucSP.IServiceDanhMucSP {
        
        public ServiceDanhMucSPClient() {
        }
        
        public ServiceDanhMucSPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDanhMucSPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDanhMucSPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDanhMucSPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WFORMKLShop.ServiceReferenceDanhMucSP.DanhMucSP[] All() {
            return base.Channel.All();
        }
        
        public System.Threading.Tasks.Task<WFORMKLShop.ServiceReferenceDanhMucSP.DanhMucSP[]> AllAsync() {
            return base.Channel.AllAsync();
        }
        
        public bool SuaDanhMuc(string madm, string tendm) {
            return base.Channel.SuaDanhMuc(madm, tendm);
        }
        
        public System.Threading.Tasks.Task<bool> SuaDanhMucAsync(string madm, string tendm) {
            return base.Channel.SuaDanhMucAsync(madm, tendm);
        }
        
        public bool XoaDanhMuc(string madm) {
            return base.Channel.XoaDanhMuc(madm);
        }
        
        public System.Threading.Tasks.Task<bool> XoaDanhMucAsync(string madm) {
            return base.Channel.XoaDanhMucAsync(madm);
        }
        
        public bool ThemDanhMuc(string madm, string tendm) {
            return base.Channel.ThemDanhMuc(madm, tendm);
        }
        
        public System.Threading.Tasks.Task<bool> ThemDanhMucAsync(string madm, string tendm) {
            return base.Channel.ThemDanhMucAsync(madm, tendm);
        }
    }
}
