//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceKLShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KLShopEntities : DbContext
    {
        public KLShopEntities()
            : base("name=KLShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CTDonHang> CTDonHangs { get; set; }
        public DbSet<CTPhieuNhap> CTPhieuNhaps { get; set; }
        public DbSet<DanhMucSP> DanhMucSPs { get; set; }
        public DbSet<DonHang> DonHangs { get; set; }
        public DbSet<PhanQuyen> PhanQuyens { get; set; }
        public DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WFCTPhieuNhap> WFCTPhieuNhaps { get; set; }
        public DbSet<WFNhapHang> WFNhapHangs { get; set; }
        public DbSet<WFPhieuNhap> WFPhieuNhaps { get; set; }
    }
}
